language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
sudo: false
before_install:
# debug
echo Will show path
echo $PATH 
# install dependencies
install: "pip install -r requirements.txt"  
language: python
python:
  - "2.7"
script: robot tests.robot
