language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
sudo: false
# install dependencies
install: "pip install -r requirements.txt" 
language: python
python:
  - "2.7"
#export PYTHON_HOME="$(python -c 'import sys; print sys.executable')"
before_script:
  export PATH=$PATH:~/bin
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/bin
  - export CHROME_BIN=chromium-browser
script: robot tests.robot
